version: "3.9"

services:
  backend_api:
    image: ${BACKEND_IMAGE}
    environment:
      PORT: "8000"

      HIK_API_BASE: "${HIK_API_BASE}"
      HIK_API_KEY: "${HIK_API_KEY}"
      HIK_POLL_INTERVAL_MS: "${HIK_POLL_INTERVAL_MS}"
      HIK_POLL_LIMIT: "${HIK_POLL_LIMIT}"

      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DATABASE: "${DB_DATABASE}"

      JWT_SECRET: "${JWT_SECRET}"

      MAIL_HOST: "${MAIL_HOST}"
      MAIL_PORT: "${MAIL_PORT}"
      MAIL_USER: "${MAIL_USER}"
      MAIL_PASS: "${MAIL_PASS}"
      MAIL_FROM: "${MAIL_FROM}"

    networks:
      - matdevnet

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: pause
      rollback_config:
        parallelism: 1
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=matdevnet"

        - "traefik.http.routers.${TRAEFIK_PREFIX}-api.rule=Host(`${APP_HOST}`) && PathPrefix(`/api`)"
        - "traefik.http.routers.${TRAEFIK_PREFIX}-api.entrypoints=websecure"
        - "traefik.http.routers.${TRAEFIK_PREFIX}-api.tls=true"
        - "traefik.http.routers.${TRAEFIK_PREFIX}-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.${TRAEFIK_PREFIX}-api.priority=100"

        - "traefik.http.middlewares.${TRAEFIK_PREFIX}-api-stripprefix.stripprefix.prefixes=/api"
        - "traefik.http.routers.${TRAEFIK_PREFIX}-api.middlewares=${TRAEFIK_PREFIX}-api-stripprefix"

        - "traefik.http.services.${TRAEFIK_PREFIX}-api.loadbalancer.server.port=8000"

  frontend_web:
    image: ${FRONTEND_IMAGE}
    networks:
      - matdevnet

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: pause
      rollback_config:
        parallelism: 1
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=matdevnet"

        - "traefik.http.routers.${TRAEFIK_PREFIX}.rule=Host(`${APP_HOST}`)"
        - "traefik.http.routers.${TRAEFIK_PREFIX}.entrypoints=websecure"
        - "traefik.http.routers.${TRAEFIK_PREFIX}.tls=true"
        - "traefik.http.routers.${TRAEFIK_PREFIX}.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.${TRAEFIK_PREFIX}.priority=1"

        - "traefik.http.services.${TRAEFIK_PREFIX}.loadbalancer.server.port=3000"

networks:
  matdevnet:
    external: true
EOF